sonar.projectKey=euroaibench-frontend
sonar.projectName=EuroAIBench Frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=src/**/*.test.tsx,src/**/*.test.ts,src/test/**,src/data/mock.ts
sonar.tests=src/__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://192.168.1.164:9000
sonar.login=squ_3d1e3dcffc17bbaaf9e390a4587b501271eb4b75
