sonar.projectKey=euroaibench-backend
sonar.projectName=EuroAIBench Backend
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.host.url=http://192.168.1.49:9000
sonar.login=squ_0029b00cf94195245fbdb7656e1b5e423ab14a1a
