"""Seed the QuantAIBench dataset: bilingual (EN/FR) quant finance questions.
Idempotent: clears questions (and dependent answers) before inserting.
Run:  python -m scripts.seed   (from /app inside the api container)
"""
from app.db.database import SessionLocal, engine, Base
from app.models.models import Question, Answer, DomainEnum, LangEnum, DifficultyEnum

Base.metadata.create_all(bind=engine)

# domain, difficulty, category, source, EN q/ref, FR q/ref
DATA = [
    # ---------------- MARKET FINANCE ----------------
    ("MARKET", "hard", "Structured products", "Bouzoubaa & Osseiran, Exotic Options",
     "Explain the payoff of a Phoenix autocall on a single underlying: coupon barrier, autocall barrier and capital-protection barrier at maturity. What is the investor's main risk?",
     "A Phoenix autocall pays a periodic conditional coupon if the underlying is at or above the coupon barrier on an observation date (often with a memory feature that recovers missed coupons). It is autocalled (redeemed early at par plus coupon) if the underlying is at or above the autocall barrier on an observation date. If never autocalled, at maturity capital is returned in full when the underlying is above the protection barrier (e.g. 60-70%); below it the investor takes the full downside one-for-one, i.e. is short a down-and-in put. Main risk: capital loss if the protection barrier is breached at maturity; the investor is effectively short volatility and short a put (and short worst-of correlation in multi-underlying versions).",
     "Expliquez le payoff d'un autocall Phoenix sur sous-jacent unique : barriere de coupon, barriere d'autocall et barriere de protection du capital a maturite. Quel est le risque principal de l'investisseur ?",
     "Un autocall Phoenix verse un coupon periodique conditionnel si le sous-jacent est au-dessus de la barriere de coupon a une date d'observation (souvent avec effet memoire qui recupere les coupons manques). Il est rappele (remboursement anticipe au pair plus coupon) si le sous-jacent depasse la barriere d'autocall a une date d'observation. S'il n'est jamais rappele, a maturite le capital est rembourse integralement si le sous-jacent est au-dessus de la barriere de protection (ex. 60-70%) ; en dessous, l'investisseur subit la baisse en totalite (un pour un), soit une position vendeuse d'un put down-and-in. Risque principal : perte en capital si la barriere de protection est franchie a maturite ; l'investisseur est de fait vendeur de volatilite et vendeur d'un put (et vendeur de correlation worst-of en multi-sous-jacents)."),
    ("MARKET", "medium", "Option Greeks", "Hull, Options Futures and Other Derivatives",
     "For a long vanilla European call, give the sign of delta, gamma, vega and theta, and state the gamma-theta relationship for a delta-hedged position.",
     "Long call: delta is positive between 0 and 1 (rising with spot); gamma is positive and largest at-the-money; vega is positive; theta is negative (time decay). For a delta-hedged long option under Black-Scholes (ignoring rates), the P&L is driven by the gamma-theta trade-off: theta is approximately minus one half sigma squared times S squared times gamma, so positive gamma (convexity benefiting from realized moves) is paid for through negative theta. The position is long gamma / long vega and profits if realized volatility exceeds implied.",
     "Pour un call europeen vanille achete, donnez le signe du delta, du gamma, du vega et du theta, et enoncez la relation gamma-theta pour une position delta-couverte.",
     "Call achete : delta positif entre 0 et 1 (croissant avec le spot) ; gamma positif, maximal a la monnaie ; vega positif ; theta negatif (decroissance temporelle). Pour une option achetee delta-couverte sous Black-Scholes (hors taux), le P&L est gouverne par l'arbitrage gamma-theta : le theta vaut environ moins un demi sigma au carre fois S au carre fois gamma ; le gamma positif (convexite profitant des mouvements realises) se paie par un theta negatif. La position est longue gamma / longue vega et gagne si la volatilite realisee depasse l'implicite."),
    # ---------------- CORPORATE FINANCE ----------------
    ("CORPORATE", "medium", "Capital structure", "Berk & DeMarzo, Corporate Finance",
     "Define the WACC and explain how it changes with leverage under Modigliani-Miller with corporate taxes.",
     "WACC equals the equity weight times the cost of equity plus the debt weight times the after-tax cost of debt: (E/V)Re + (D/V)Rd(1-Tc). Under Modigliani-Miller without taxes, firm value is independent of capital structure (Proposition I) and the cost of equity rises linearly with the debt-to-equity ratio (Proposition II), leaving WACC constant. With corporate taxes the interest tax shield makes the levered value equal the unlevered value plus Tc times debt, so WACC declines as leverage increases (toward Rd(1-Tc)). Trade-off theory adds financial-distress and agency costs, giving an interior optimal leverage rather than 100% debt.",
     "Definissez le WACC et expliquez comment il evolue avec le levier sous Modigliani-Miller avec impot sur les societes.",
     "Le WACC est le poids des fonds propres fois le cout des fonds propres plus le poids de la dette fois le cout de la dette apres impot : (E/V)Re + (D/V)Rd(1-Tc). Sous Modigliani-Miller sans impot, la valeur de l'entreprise est independante de la structure du capital (Proposition I) et le cout des fonds propres croit lineairement avec le ratio dette/fonds propres (Proposition II), si bien que le WACC reste constant. Avec l'impot societe, l'economie d'impot sur les interets rend la valeur avec levier egale a la valeur sans levier plus Tc fois la dette : le WACC decroit donc quand le levier augmente (vers Rd(1-Tc)). La theorie du compromis ajoute les couts de detresse financiere et d'agence, donnant un levier optimal interieur plutot que 100% de dette."),
    ("CORPORATE", "medium", "Valuation", "Damodaran, Investment Valuation",
     "How do you value a company with an unlevered DCF (FCFF)? Define FCFF and the Gordon-growth terminal value.",
     "Free cash flow to the firm is EBIT times (1 minus the tax rate) plus depreciation and amortization, minus capital expenditure, minus the change in net working capital. Discount the projected FCFF at the WACC. Enterprise value is the sum of discounted FCFF over the explicit horizon plus the discounted terminal value; the Gordon-growth terminal value is next-year FCFF divided by (WACC minus the perpetual growth rate g), with g strictly below WACC. Equity value equals enterprise value minus net debt (and minority interests), divided by shares for per-share value.",
     "Comment valoriser une entreprise par DCF sans levier (FCFF) ? Definissez le FCFF et la valeur terminale par croissance de Gordon.",
     "Le free cash flow to firm vaut l'EBIT fois (1 moins le taux d'impot) plus les dotations aux amortissements, moins les investissements (capex), moins la variation du besoin en fonds de roulement. On actualise les FCFF projetes au WACC. La valeur d'entreprise est la somme des FCFF actualises sur l'horizon explicite plus la valeur terminale actualisee ; la valeur terminale de Gordon vaut le FCFF de l'annee suivante divise par (WACC moins le taux de croissance perpetuel g), avec g strictement inferieur au WACC. La valeur des fonds propres egale la valeur d'entreprise moins la dette nette (et les minoritaires)."),
    # ---------------- PROJECT FINANCE ----------------
    ("PROJECT", "hard", "Debt sizing", "Yescombe, Principles of Project Finance",
     "What is the DSCR in project finance and how is it used to size and sculpt debt? Mention the LLCR.",
     "The Debt Service Coverage Ratio is cash flow available for debt service (CFADS) divided by scheduled debt service (principal plus interest) in a period. Lenders impose a minimum DSCR (for example 1.30x for a contracted infrastructure project). Debt is sized so that each period's debt service equals CFADS divided by the target DSCR, which sculpts the repayment profile to the cash flows rather than using straight-line amortization. The Loan Life Coverage Ratio, the present value of CFADS over the loan life divided by debt outstanding, is a complementary forward-looking metric. A debt-service reserve account and cash sweeps provide further protection.",
     "Qu'est-ce que le DSCR en project finance et comment l'utilise-t-on pour dimensionner et sculpter la dette ? Mentionnez le LLCR.",
     "Le Debt Service Coverage Ratio est le flux de tresorerie disponible pour le service de la dette (CFADS) divise par le service de la dette programme (principal plus interets) sur une periode. Les preteurs imposent un DSCR minimum (par exemple 1,30x pour une infrastructure sous contrat). La dette est dimensionnee de sorte que le service de chaque periode egale le CFADS divise par le DSCR cible, ce qui sculpte le profil de remboursement sur les flux plutot qu'un amortissement lineaire. Le Loan Life Coverage Ratio, valeur actuelle des CFADS sur la duree du pret divisee par la dette en cours, est une mesure prospective complementaire. Un compte de reserve du service de la dette et des cash sweeps renforcent la protection."),
    ("PROJECT", "medium", "Structuring", "Gatti, Project Finance in Theory and Practice",
     "Why is project finance built around an SPV with non-recourse debt, and what does ring-fencing achieve?",
     "A special purpose vehicle isolates the project's assets and cash flows in a standalone entity so that lenders rely on the project's own CFADS rather than the sponsors' balance sheet; the debt is non-recourse or limited-recourse to the sponsors. Ring-fencing legally separates the project from sponsor risk in both directions: sponsors are shielded from project liabilities, and lenders are protected from sponsor bankruptcy. Lenders take security over the project's assets, contracts and bank accounts, and rely on the contractual framework (offtake, supply, construction). Subject to accounting consolidation rules, this can keep the debt off the sponsors' balance sheet.",
     "Pourquoi le project finance est-il structure autour d'une SPV a dette sans recours, et que permet le ring-fencing ?",
     "Une societe de projet (SPV) isole les actifs et les flux du projet dans une entite autonome, de sorte que les preteurs s'appuient sur les CFADS du projet plutot que sur le bilan des sponsors ; la dette est sans recours ou a recours limite envers les sponsors. Le ring-fencing separe juridiquement le projet du risque sponsor dans les deux sens : les sponsors sont proteges des passifs du projet, et les preteurs sont proteges de la faillite des sponsors. Les preteurs prennent des suretes sur les actifs, contrats et comptes du projet et s'appuient sur le cadre contractuel (offtake, fourniture, construction). Sous reserve des regles de consolidation comptable, cela peut maintenir la dette hors bilan des sponsors."),
    # ---------------- RISK MANAGEMENT ----------------
    ("RISK", "hard", "Market risk", "Artzner et al.; Basel FRTB",
     "Define 99% one-day VaR and Expected Shortfall. Why did Basel FRTB move from VaR to ES, and is VaR a coherent risk measure?",
     "One-day 99% Value-at-Risk is the loss level that is not exceeded with 99% probability over a one-day horizon, i.e. the 99% quantile of the loss distribution. Expected Shortfall at level alpha is the expected loss conditional on the loss exceeding the VaR at that level, so it averages the tail beyond VaR. Expected Shortfall is a coherent risk measure (it is sub-additive, satisfying the Artzner et al. axioms), whereas VaR is not sub-additive in general and can penalize diversification, so it fails coherence. Basel's Fundamental Review of the Trading Book replaced VaR with a 97.5% Expected Shortfall to better capture tail risk.",
     "Definissez la VaR un jour a 99% et l'Expected Shortfall. Pourquoi Bale FRTB est-il passe de la VaR a l'ES, et la VaR est-elle une mesure de risque coherente ?",
     "La Value-at-Risk un jour a 99% est le niveau de perte qui n'est pas depasse avec une probabilite de 99% sur un horizon d'un jour, soit le quantile a 99% de la distribution des pertes. L'Expected Shortfall au niveau alpha est la perte esperee conditionnellement au depassement de la VaR a ce niveau ; elle moyenne la queue au-dela de la VaR. L'Expected Shortfall est une mesure de risque coherente (sous-additive, satisfaisant les axiomes d'Artzner et al.), alors que la VaR n'est pas sous-additive en general et peut penaliser la diversification, donc elle n'est pas coherente. La revue fondamentale du portefeuille de negociation de Bale (FRTB) a remplace la VaR par une Expected Shortfall a 97,5% pour mieux capter le risque de queue."),
    ("RISK", "hard", "Counterparty risk / xVA", "Gregory, The xVA Challenge",
     "What is CVA, how is it computed, and what are its main drivers? Situate it within xVA.",
     "Credit Valuation Adjustment is the market value of counterparty default risk on a derivatives portfolio: the price the bank charges for the chance the counterparty defaults while owing money. It is computed as loss-given-default times the integral (or discounted sum) of expected positive exposure multiplied by the counterparty's default probability density, with all cash flows discounted. Its main drivers are the expected positive exposure profile, the counterparty's credit spread (default probabilities implied from CDS), recovery / LGD, and any correlation between exposure and credit quality (wrong-way risk). CVA is one of the xVA family alongside DVA (own default), FVA (funding), and capital and margin adjustments (KVA, MVA).",
     "Qu'est-ce que la CVA, comment la calcule-t-on et quels sont ses principaux moteurs ? Situez-la dans les xVA.",
     "La Credit Valuation Adjustment est la valeur de marche du risque de defaut de la contrepartie sur un portefeuille de derives : le prix facture pour la probabilite que la contrepartie fasse defaut en etant debitrice. Elle se calcule comme la perte en cas de defaut (LGD) fois l'integrale (ou la somme actualisee) de l'exposition positive esperee multipliee par la densite de probabilite de defaut de la contrepartie, tous les flux etant actualises. Ses moteurs principaux sont le profil d'exposition positive esperee, le spread de credit de la contrepartie (probabilites de defaut implicites des CDS), le taux de recouvrement / LGD, et toute correlation entre exposition et qualite de credit (wrong-way risk). La CVA appartient a la famille des xVA aux cotes de la DVA (propre defaut), de la FVA (financement) et des ajustements de capital et de marge (KVA, MVA)."),
    # ---------------- QUANT STRATEGIES ----------------
    ("QUANT", "medium", "Performance metrics", "Bailey & Lopez de Prado",
     "Define the Sharpe ratio and the Information ratio. How are they annualized and what are the main pitfalls?",
     "The Sharpe ratio is the portfolio's excess return over the risk-free rate divided by the standard deviation of returns. The Information ratio is the active return relative to a benchmark divided by the tracking error. Assuming independent and identically distributed returns, the mean scales with the number of periods N and the standard deviation with the square root of N, so the Sharpe ratio annualizes by multiplying by the square root of N. Pitfalls: returns are often non-normal and autocorrelated, which inflates a naively scaled Sharpe; the metric ignores skewness and kurtosis (tail risk); and in-sample optimization produces overfit, upward-biased Sharpe ratios (the deflated Sharpe ratio corrects for multiple testing).",
     "Definissez le ratio de Sharpe et le ratio d'information. Comment les annualise-t-on et quels sont les principaux pieges ?",
     "Le ratio de Sharpe est le rendement excedentaire du portefeuille au-dessus du taux sans risque divise par l'ecart-type des rendements. Le ratio d'information est le rendement actif relatif a un indice de reference divise par la tracking error. En supposant des rendements independants et identiquement distribues, la moyenne croit avec le nombre de periodes N et l'ecart-type avec la racine de N, donc le ratio de Sharpe s'annualise en le multipliant par la racine de N. Pieges : les rendements sont souvent non normaux et autocorreles, ce qui gonfle un Sharpe naivement mis a l'echelle ; la mesure ignore l'asymetrie et l'aplatissement (risque de queue) ; et l'optimisation en echantillon produit des Sharpe surajustes et biaises a la hausse (le deflated Sharpe ratio corrige le test multiple)."),
    ("QUANT", "medium", "Factor investing", "Fama & French; Carhart",
     "Explain the Fama-French three-factor model and what factor investing seeks to exploit.",
     "The Fama-French three-factor model explains a stock's excess return by its sensitivity to three factors: the market excess return (as in CAPM), a size factor (small minus big, SMB) and a value factor (high minus low book-to-market, HML). It improves on CAPM by capturing the historical outperformance of small-cap and value stocks. Factor investing seeks to harvest persistent risk premia, value, size, momentum, quality and low-volatility, through systematic long/short portfolios or long-only tilts, rather than relying on stock picking. Carhart extended the model with a momentum factor, giving the four-factor model; later work added profitability and investment (the five-factor model).",
     "Expliquez le modele a trois facteurs de Fama-French et ce que cherche a exploiter le factor investing.",
     "Le modele a trois facteurs de Fama-French explique le rendement excedentaire d'une action par sa sensibilite a trois facteurs : le rendement excedentaire du marche (comme dans le CAPM), un facteur de taille (small minus big, SMB) et un facteur de valeur (high minus low book-to-market, HML). Il ameliore le CAPM en captant la surperformance historique des petites capitalisations et des titres value. Le factor investing cherche a recolter des primes de risque persistantes, value, taille, momentum, qualite et faible volatilite, via des portefeuilles long/short systematiques ou des biais long-only, plutot que par la selection de titres. Carhart a ajoute un facteur momentum, donnant le modele a quatre facteurs ; des travaux ulterieurs ont ajoute la profitabilite et l'investissement (modele a cinq facteurs)."),
    # ---------------- FIXED INCOME & RATES ----------------
    ("RATES", "medium", "Bond risk", "Fabozzi, Bond Markets Analysis and Strategies",
     "Define modified duration and convexity and give the second-order approximation of a bond's price change for a yield move.",
     "Modified duration is the first-order sensitivity of a bond's price to its yield: it equals the Macaulay duration divided by one plus the periodic yield, and measures the approximate percentage price change for a small yield move. Convexity is the second-order term, the curvature of the price-yield relationship. The second-order approximation of the relative price change is minus modified duration times the yield change, plus one half times convexity times the yield change squared. For option-free bonds convexity is positive, which benefits the holder: prices rise more than duration predicts when yields fall and fall less when yields rise. Callable bonds can exhibit negative convexity.",
     "Definissez la duration modifiee et la convexite, et donnez l'approximation au second ordre de la variation de prix d'une obligation pour un mouvement de taux.",
     "La duration modifiee est la sensibilite au premier ordre du prix d'une obligation a son taux : elle vaut la duration de Macaulay divisee par un plus le taux periodique et mesure la variation relative approximative du prix pour un petit mouvement de taux. La convexite est le terme du second ordre, la courbure de la relation prix-taux. L'approximation au second ordre de la variation relative de prix est moins la duration modifiee fois la variation de taux, plus un demi fois la convexite fois la variation de taux au carre. Pour les obligations sans option la convexite est positive, ce qui profite au detenteur : les prix montent plus que ne le predit la duration quand les taux baissent et baissent moins quand les taux montent. Les obligations remboursables par anticipation peuvent presenter une convexite negative."),
    ("RATES", "hard", "Swaps", "Hull; OIS discounting literature",
     "How is a vanilla fixed-for-floating interest rate swap valued at inception, what is the par swap rate, and why does multi-curve / OIS discounting matter?",
     "A vanilla swap's value is the present value of the floating leg minus the present value of the fixed leg (from the fixed payer's view). At inception the fixed rate is set so the value is zero: the par swap rate equals the sum of discounted forward rates times accruals divided by the sum of discount factors times accruals (the annuity), so it equates the present values of the two legs. After 2008 the market moved to a multi-curve framework: floating cash flows are projected off the relevant forward (projection) curve such as SOFR or ESTR, while cash flows are discounted on the overnight-indexed-swap curve because collateralized trades are funded at the collateral rate. Using a single curve would misprice the swap and ignore the basis between projection and discounting.",
     "Comment valorise-t-on un swap de taux vanille taux fixe contre taux variable a l'initiation, qu'est-ce que le taux swap de marche, et pourquoi le multi-courbe / l'actualisation OIS importe-t-il ?",
     "La valeur d'un swap vanille est la valeur actuelle de la jambe variable moins celle de la jambe fixe (du point de vue du payeur du fixe). A l'initiation, le taux fixe est fixe pour que la valeur soit nulle : le taux swap de marche egale la somme des taux forward actualises ponderes par les accruals divisee par la somme des facteurs d'actualisation ponderes par les accruals (l'annuite), ce qui egalise les valeurs actuelles des deux jambes. Apres 2008, le marche est passe a un cadre multi-courbe : les flux variables sont projetes sur la courbe forward (de projection) pertinente comme SOFR ou ESTR, tandis que les flux sont actualises sur la courbe des swaps indexes au jour le jour (OIS) car les operations collateralisees sont financees au taux du collateral. Utiliser une seule courbe mal-valoriserait le swap et ignorerait la base entre projection et actualisation."),
]

def run():
    db = SessionLocal()
    try:
        db.query(Answer).delete()
        db.query(Question).delete()
        db.commit()
        n = 0
        for domain, diff, cat, src, q_en, r_en, q_fr, r_fr in DATA:
            db.add(Question(domain=DomainEnum[domain], language=LangEnum.EN,
                            difficulty=DifficultyEnum[diff], category=cat,
                            question=q_en, reference_answer=r_en, source_ref=src))
            db.add(Question(domain=DomainEnum[domain], language=LangEnum.FR,
                            difficulty=DifficultyEnum[diff], category=cat,
                            question=q_fr, reference_answer=r_fr, source_ref=src))
            n += 2
        db.commit()
        print(f"Seeded {n} questions ({len(DATA)} distinct x 2 languages) across 6 domains.")
    finally:
        db.close()

if __name__ == "__main__":
    run()
